// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tms.Orders.Infrastructure.Persistence;

#nullable disable

namespace Tms.Orders.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    partial class OrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ord")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tms.Orders.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DGClass")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDangerousGoods")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SKU")
                        .HasColumnType("text");

                    b.Property<string>("UNNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("Volume")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", "ord");
                });

            modelBuilder.Entity("Tms.Orders.Domain.Entities.TransportOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("TransportOrders", "ord");
                });

            modelBuilder.Entity("Tms.Orders.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Tms.Orders.Domain.Entities.TransportOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tms.Orders.Domain.Entities.TransportOrder", b =>
                {
                    b.OwnsOne("Tms.Orders.Domain.ValueObjects.Address", "DropoffAddress", b1 =>
                        {
                            b1.Property<Guid>("TransportOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("DropoffDistrict");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("DropoffLat");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("DropoffLng");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("DropoffPostalCode");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("DropoffProvince");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("DropoffStreet");

                            b1.Property<string>("SubDistrict")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("DropoffSubDistrict");

                            b1.HasKey("TransportOrderId");

                            b1.ToTable("TransportOrders", "ord");

                            b1.WithOwner()
                                .HasForeignKey("TransportOrderId");
                        });

                    b.OwnsOne("Tms.Orders.Domain.ValueObjects.TimeWindow", "DropoffWindow", b1 =>
                        {
                            b1.Property<Guid>("TransportOrderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("From")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DropoffFrom");

                            b1.Property<DateTime>("To")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DropoffTo");

                            b1.HasKey("TransportOrderId");

                            b1.ToTable("TransportOrders", "ord");

                            b1.WithOwner()
                                .HasForeignKey("TransportOrderId");
                        });

                    b.OwnsOne("Tms.Orders.Domain.ValueObjects.Address", "PickupAddress", b1 =>
                        {
                            b1.Property<Guid>("TransportOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PickupDistrict");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("PickupLat");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("PickupLng");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("PickupPostalCode");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PickupProvince");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("PickupStreet");

                            b1.Property<string>("SubDistrict")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PickupSubDistrict");

                            b1.HasKey("TransportOrderId");

                            b1.ToTable("TransportOrders", "ord");

                            b1.WithOwner()
                                .HasForeignKey("TransportOrderId");
                        });

                    b.OwnsOne("Tms.Orders.Domain.ValueObjects.TimeWindow", "PickupWindow", b1 =>
                        {
                            b1.Property<Guid>("TransportOrderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("From")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PickupFrom");

                            b1.Property<DateTime>("To")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PickupTo");

                            b1.HasKey("TransportOrderId");

                            b1.ToTable("TransportOrders", "ord");

                            b1.WithOwner()
                                .HasForeignKey("TransportOrderId");
                        });

                    b.Navigation("DropoffAddress")
                        .IsRequired();

                    b.Navigation("DropoffWindow");

                    b.Navigation("PickupAddress")
                        .IsRequired();

                    b.Navigation("PickupWindow");
                });

            modelBuilder.Entity("Tms.Orders.Domain.Entities.TransportOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
